about/urls.py
from . import views
from django.conf.urls import url

app_name = 'about'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

contact/urls.py
from . import views
from django.conf.urls import url

app_name = 'contact'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

equipment/urls.py
from . import views
from django.conf.urls import url

app_name = 'equipment'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

faqs/urls.py
from . import views
from django.conf.urls import url

app_name = 'faqs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

moldyWebsite/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home:index'), permanent=False)),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^equipment/', include('equipment.urls')),
    url(r'^faqs/', include('faqs.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^reference/', include('reference.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#######
# IMPORTANT!!!!!
# Once in production, remove the + static(...) bit, it is unsafe.

products/urls.py
from django.conf.urls import url
from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<product_slug>[\w-]+)/$', views.detail, name='detail'),
]

common/models.py
from django.db import models
import markdown



class GalleryImage(models.Model):
    """
    Abstract base class for gallery images.

    Recommended when implementing: have a parent ForeignKey field.

    Attributes:
        position - Determines the order in which to display the images in the gallery.
                   The category with the lowest position value should be displayed first,
                   the largest position value should be displayed last.
        title - A title that might be displayed to users in the gallery.
        info - A caption or other misc info that may be displayed to users in the gallery.
        image - The image that is to be displayed.
    """
    position = models.PositiveIntegerField()
    title = models.CharField(max_length=500)
    info = models.TextField()
    image = models.ImageField(upload_to='images/galleries')

    class Meta:
        abstract = True



class MarkdownImage(models.Model):
    """
    An image that is assosiated with a MarkdownModel.
    """
    name = models.CharField(max_length=250)
    image = models.ImageField(upload_to='images')
    parent = models.ForeignKey('MarkdownModel', on_delete=models.CASCADE)



class MarkdownModel(models.Model):
    """
    A base class for models which require a simple markdown field.

    Can't be made abstract since MarkdownImage references MarkdownModel.
    """
    markdown = models.TextField()
    html = models.TextField()

    def convert_markdown(self):
        """
        Converts the markdown to html. This code is a modified version of
        Ole Morten Halvorsen's implementation, found here:
        http://www.omh.cc/blog/2008/aug/18/django-inserting-and-positioning-images/
        """
        image_refs = ''

        for image in self.markdownimage_set.all():
            image_url = image.image.url
            image_refs += '\n[{0}]: {1}'.format(image.name, image_url)

        return markdown.markdown('{0}\n{1}'.format(self.markdown, image_refs))

    def save(self):
        self.html = self.convert_markdown()
        super(MarkdownModel, self).save()

common/views.py
from django.shortcuts import render



def basicPage(request, template_name, additional_context):
    """
    Generates a basic page with the default header and footer. The active page is
    highlighted in the nav-menu based on the request path.

    Acts exactly like django.shortcuts.render but appends the nav_item_list to the context
    so that it dosn't have to be included multiple times.

    args:
        request - The standard HTTP request.
        template_name - The name of the template to render. The template should extend
                        common/base.html.
        context - Additional context for use in the template extension only. All context
                  required by base.html should already be inlcuded in this function.
    """
    context = {}
    context.update(additional_context)  # Add additional items.
    return render(request, template_name, context)

common/templates/common/includes/navbar.html
{% load common_extras %}

<!-- Note: We assume that bootstrap is loaded in the source template -->



<nav class="navbar navbar-default navbar-static-top">
    <div class="container">

        <!-- Uncollpasable content -->
        <div class="navbar-header">
            <a class="navbar-brand noselect" href="{% url 'home:index' %}" >Molds America LLC</a>

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>



        <!-- Collapsable content -->
        <div class="collapse navbar-collapse" id="main-navbar">
            <ul class="nav navbar-nav navbar-right">
                <li class="{% app_active request 'products' %}"><a href="{% url 'products:index' %}">Products</a></li>
                <li class="{% app_active request 'equipment' %}"><a href="{% url 'equipment:index' %}">Equipment</a></li>
                <li class="{% app_active request 'about' %}"><a href="{% url 'about:index' %}">About</a></li>
                <li class="{% app_active request 'contact' %}"><a href="{% url 'contact:index' %}">Contact</a></li>
                <li class="{% app_active request 'faqs' %}"><a href="{% url 'faqs:index' %}">FAQs</a></li>
                <li class="{% app_active request 'reference' %}"><a href="{% url 'reference:index' %}">Reference</a></li>
            </ul>
        </div>

    </div>
</nav>