faqs/urls.py
from . import views
from django.conf.urls import url

app_name = 'faqs'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

moldyWebsite/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=reverse_lazy('home:index'), permanent=False)),
    url(r'^about/', include('about.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^equipment/', include('equipment.urls')),
    url(r'^faqs/', include('faqs.urls')),
    url(r'^home/', include('home.urls')),
    url(r'^products/', include('products.urls')),
    url(r'^reference/', include('reference.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#######
# IMPORTANT!!!!!
# Once in production, remove the + static(...) bit, it is unsafe.

products/urls.py
from django.conf.urls import url
from . import views

app_name = 'products'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<product_slug>[\w-]+)/$', views.detail, name='detail'),
]

products/models.py
from common.models import GalleryImage, MarkdownModel
from django.db import models



class Product(MarkdownModel):
    """
    A model describing projects that have been completed.

    Attributes:
        position - Determines the order in which to display the products on the page.
                   The category with the lowest position value should be displayed first,
                   the largest position value should be displayed last.
        slug - The slug for the project page.
        name - The name of the product.
        short_desc - A short description to be displayed on the product index page.
        long_desc - A longer description that thoughly explains the project in depth.
                    Should be displayed on the project page.
        completion_date - The date that the project was completed. Null if unfinished.
        thumbnail - A thumbnail to be displayed on the product index page.
    """
    position = models.PositiveIntegerField()
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=1000)
    short_desc = models.TextField()
    completion_date = models.DateField(null=True)
    thumbnail = models.ImageField(upload_to='products/images/thumbnails')

    class Meta:
        ordering = ['position', 'name']

    def __str__(self):
        return self.name



class ProductGalleryImage(GalleryImage):
    """
    Images to be displayed in a gallery for a product.
    """
    parent = models.ForeignKey('Product', on_delete=models.CASCADE)

products/views.py
from .models import Product
from common.views import basicPage

def index(request):
    context = {
        'products': Product.objects.all(),
    }
    return basicPage(request, 'products/base_products.html', context)


def detail(request, product_slug):
    context = {
        'product': Product.objects.get(slug=product_slug),
    }
    return basicPage(request, 'products/product_detail.html', context)

products/templates/products/base_products.html
{% extends "common/base.html" %}
{% load static %}



{% block subheader_content %}
<a href="{% url 'products:index' %}">Look over our past work.</a>
{% endblock %}



{% block main_content %}
<div class="row">
    {% for product in products %}
    <div class="col-md-4 gallery-entry">
        <a href="{% url 'products:detail' product.slug %}">
            <h3>{{ product.name }}</h3>
            <img src="{{ product.thumbnail.url }}" alt="{{ product.name }} Thumbnail"/>
            <div class="caption">
                {{ product.short_desc }}
            </div>
        </a>
    </div>
    {% endfor %}
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "common/base.html" %}
{% load static %}



{% block additional_resources %}
<script type="text/javascript">
    $(document).ready(function(){
        // Activate first item in carousel.
        $('.carousel .item').first().addClass('active');
        $('.carousel .carousel-indicators li').first().addClass('active');
    });
</script>
{% endblock %}



{% block subheader_content %}
<a href="{% url 'products:index' %}">Look over our past work.</a>
{% endblock %}



{% block main_content %}

<h1>{{ product.name }}</h1>

<div>
    {{ product.html|safe }}
</div>

<div id="gallery-carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {% for image in product.productgalleryimage_set.all %}
        <li data-target="#gallery-carousel" data-slide-to="{{ forloop.counter|add:'-1' }}"></li>
        {% endfor %}
    </ol>

    <!-- Slides -->
    <div class="carousel-inner" role="listbox">
        {% for image in product.productgalleryimage_set.all %}
        <div class="item">
            <img src="{{ image.image.url }}" alt="{{ image.title }}">
            <div class="carousel-caption">
                <h3>{{ image.title }}</h3>
                <p>{{ image.info }}</p>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#gallery-carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
    <a class="right carousel-control" href="#gallery-carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </a>
</div>
{% endblock %}